
spring:
  application:
    name: test-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/qa_test?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&useServerPrepareStatement=true
    username: root
    password: ${MYSQL_PASSWORD:1234}
    initialization-mode: always

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework: DEBUG
    com.netflix: DEBUG

question:
  url: http://localhost:8082

# host.docker.internal: 192.168.8.100

#reactive:
#  feign:
#    client:
#      config:
#        question-service:
#          options:
#            readTimeoutMillis: 2000
#            writeTimeoutMillis: 2000
#            responseTimeoutMillis: 2000