
spring:
  application:
    name: service-registry

server:
  port: 8761


logging:
  level:
    org.springframework: DEBUG
    com.netflix: DEBUG

eureka:
  instance:
  client:
    hostname: localhost
    fetch-registry: false
    register-with-eureka: false


