
spring:
  application:
    name: question-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/qa_question?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&useServerPrepareStatement=true
    username: root
    password: ${MYSQL_PASSWORD:1234}
    initialization-mode: always
# host.docker.internal: 192.168.8.100
#eureka:
#  client:
#    service-url:
#      defaultZone: http://172.20.80.1:8761/eureka/

logging:
  level:
    org.springframework: DEBUG
    com.netflix: DEBUG


server:
  port: 8082
