
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/qa_question?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&useServerPrepareStatement=true
    username: root
    password: ${MYSQL_PASSWORD:1234}
    initialization-mode: always

server:
  port: 7070
